"""Static data for all 118 elements of the periodic table.

Grid coordinates (`period`, `group`) follow the standard 18-group layout,
with lanthanides and actinides placed on two separate rows below the main
body (periods 8 and 9 in this grid, groups 3-17).
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class Element:
    number: int
    symbol: str
    name: str
    mass: float
    category: str
    period: int
    group: int
    summary: str


CATEGORY_COLORS: dict[str, str] = {
    "alkali metal": "#ff8a65",
    "alkaline earth metal": "#ffd54f",
    "transition metal": "#90caf9",
    "post-transition metal": "#a5d6a7",
    "metalloid": "#ce93d8",
    "reactive nonmetal": "#fff59d",
    "noble gas": "#80deea",
    "lanthanide": "#f48fb1",
    "actinide": "#ef9a9a",
    "unknown": "#bdbdbd",
}

ELEMENTS: list[Element] = [
    Element(1, "H", "Hydrogen", 1.008, "reactive nonmetal", 1, 1, "Lightest and most abundant element in the universe."),
    Element(2, "He", "Helium", 4.0026, "noble gas", 1, 18, "Inert gas used in balloons and cryogenics."),
    Element(3, "Li", "Lithium", 6.94, "alkali metal", 2, 1, "Soft metal used in rechargeable batteries."),
    Element(4, "Be", "Beryllium", 9.0122, "alkaline earth metal", 2, 2, "Lightweight, brittle metal used in aerospace alloys."),
    Element(5, "B", "Boron", 10.81, "metalloid", 2, 13, "Used in glass, ceramics, and detergents."),
    Element(6, "C", "Carbon", 12.011, "reactive nonmetal", 2, 14, "Basis of all known organic life."),
    Element(7, "N", "Nitrogen", 14.007, "reactive nonmetal", 2, 15, "Makes up about 78% of Earth's atmosphere."),
    Element(8, "O", "Oxygen", 15.999, "reactive nonmetal", 2, 16, "Essential for respiration in most life forms."),
    Element(9, "F", "Fluorine", 18.998, "reactive nonmetal", 2, 17, "Most reactive and electronegative element."),
    Element(10, "Ne", "Neon", 20.180, "noble gas", 2, 18, "Used in glowing electric signs."),
    Element(11, "Na", "Sodium", 22.990, "alkali metal", 3, 1, "Reacts violently with water; found in table salt."),
    Element(12, "Mg", "Magnesium", 24.305, "alkaline earth metal", 3, 2, "Lightweight structural metal, burns brightly."),
    Element(13, "Al", "Aluminium", 26.982, "post-transition metal", 3, 13, "Lightweight metal widely used in packaging and transport."),
    Element(14, "Si", "Silicon", 28.085, "metalloid", 3, 14, "Backbone of semiconductors and computer chips."),
    Element(15, "P", "Phosphorus", 30.974, "reactive nonmetal", 3, 15, "Essential for DNA, RNA, and ATP."),
    Element(16, "S", "Sulfur", 32.06, "reactive nonmetal", 3, 16, "Yellow solid used in fertilizers and matches."),
    Element(17, "Cl", "Chlorine", 35.45, "reactive nonmetal", 3, 17, "Yellow-green gas used for water disinfection."),
    Element(18, "Ar", "Argon", 39.948, "noble gas", 3, 18, "Inert gas used in welding and light bulbs."),
    Element(19, "K", "Potassium", 39.098, "alkali metal", 4, 1, "Essential electrolyte for nerve and muscle function."),
    Element(20, "Ca", "Calcium", 40.078, "alkaline earth metal", 4, 2, "Key component of bones and teeth."),
    Element(21, "Sc", "Scandium", 44.956, "transition metal", 4, 3, "Rare metal used in aerospace alloys."),
    Element(22, "Ti", "Titanium", 47.867, "transition metal", 4, 4, "Strong, corrosion-resistant metal used in aircraft."),
    Element(23, "V", "Vanadium", 50.942, "transition metal", 4, 5, "Used to strengthen steel alloys."),
    Element(24, "Cr", "Chromium", 51.996, "transition metal", 4, 6, "Gives stainless steel its corrosion resistance."),
    Element(25, "Mn", "Manganese", 54.938, "transition metal", 4, 7, "Essential for steel production."),
    Element(26, "Fe", "Iron", 55.845, "transition metal", 4, 8, "Most widely used structural metal on Earth."),
    Element(27, "Co", "Cobalt", 58.933, "transition metal", 4, 9, "Used in rechargeable battery cathodes."),
    Element(28, "Ni", "Nickel", 58.693, "transition metal", 4, 10, "Corrosion-resistant metal used in coins and alloys."),
    Element(29, "Cu", "Copper", 63.546, "transition metal", 4, 11, "Excellent electrical conductor used in wiring."),
    Element(30, "Zn", "Zinc", 65.38, "transition metal", 4, 12, "Used to galvanize steel against corrosion."),
    Element(31, "Ga", "Gallium", 69.723, "post-transition metal", 4, 13, "Melts near room temperature; used in semiconductors."),
    Element(32, "Ge", "Germanium", 72.630, "metalloid", 4, 14, "Used in fiber optics and infrared devices."),
    Element(33, "As", "Arsenic", 74.922, "metalloid", 4, 15, "Toxic metalloid used in semiconductors."),
    Element(34, "Se", "Selenium", 78.971, "reactive nonmetal", 4, 16, "Essential trace element; used in photocells."),
    Element(35, "Br", "Bromine", 79.904, "reactive nonmetal", 4, 17, "One of only two liquid elements at room temperature."),
    Element(36, "Kr", "Krypton", 83.798, "noble gas", 4, 18, "Used in high-performance lighting."),
    Element(37, "Rb", "Rubidium", 85.468, "alkali metal", 5, 1, "Highly reactive soft metal used in atomic clocks."),
    Element(38, "Sr", "Strontium", 87.62, "alkaline earth metal", 5, 2, "Used in fireworks for red coloration."),
    Element(39, "Y", "Yttrium", 88.906, "transition metal", 5, 3, "Used in LEDs and superconductors."),
    Element(40, "Zr", "Zirconium", 91.224, "transition metal", 5, 4, "Corrosion-resistant, used in nuclear reactors."),
    Element(41, "Nb", "Niobium", 92.906, "transition metal", 5, 5, "Used in superconducting magnets."),
    Element(42, "Mo", "Molybdenum", 95.95, "transition metal", 5, 6, "High melting point metal used in steel alloys."),
    Element(43, "Tc", "Technetium", 98.0, "transition metal", 5, 7, "First artificially produced element."),
    Element(44, "Ru", "Ruthenium", 101.07, "transition metal", 5, 8, "Rare metal used as a catalyst."),
    Element(45, "Rh", "Rhodium", 102.91, "transition metal", 5, 9, "Used in catalytic converters."),
    Element(46, "Pd", "Palladium", 106.42, "transition metal", 5, 10, "Used in catalytic converters and electronics."),
    Element(47, "Ag", "Silver", 107.87, "transition metal", 5, 11, "Best electrical conductor of all metals."),
    Element(48, "Cd", "Cadmium", 112.41, "transition metal", 5, 12, "Used in rechargeable nickel-cadmium batteries."),
    Element(49, "In", "Indium", 114.82, "post-transition metal", 5, 13, "Used in touchscreens and LCD displays."),
    Element(50, "Sn", "Tin", 118.71, "post-transition metal", 5, 14, "Used to coat steel cans and in solder."),
    Element(51, "Sb", "Antimony", 121.76, "metalloid", 5, 15, "Used in flame retardants and alloys."),
    Element(52, "Te", "Tellurium", 127.60, "metalloid", 5, 16, "Used in solar panels and alloys."),
    Element(53, "I", "Iodine", 126.90, "reactive nonmetal", 5, 17, "Essential for thyroid hormone production."),
    Element(54, "Xe", "Xenon", 131.29, "noble gas", 5, 18, "Used in high-intensity lamps and ion propulsion."),
    Element(55, "Cs", "Caesium", 132.91, "alkali metal", 6, 1, "Defines the second via atomic clocks."),
    Element(56, "Ba", "Barium", 137.33, "alkaline earth metal", 6, 2, "Used in medical imaging contrast agents."),
    Element(57, "La", "Lanthanum", 138.91, "lanthanide", 9, 3, "Used in camera lenses and catalysts."),
    Element(58, "Ce", "Cerium", 140.12, "lanthanide", 9, 4, "Most abundant rare-earth element."),
    Element(59, "Pr", "Praseodymium", 140.91, "lanthanide", 9, 5, "Used in aircraft engine alloys and magnets."),
    Element(60, "Nd", "Neodymium", 144.24, "lanthanide", 9, 6, "Used in powerful permanent magnets."),
    Element(61, "Pm", "Promethium", 145.0, "lanthanide", 9, 7, "Rare radioactive element with no stable isotopes."),
    Element(62, "Sm", "Samarium", 150.36, "lanthanide", 9, 8, "Used in samarium-cobalt magnets."),
    Element(63, "Eu", "Europium", 151.96, "lanthanide", 9, 9, "Used as a red phosphor in displays."),
    Element(64, "Gd", "Gadolinium", 157.25, "lanthanide", 9, 10, "Used in MRI contrast agents."),
    Element(65, "Tb", "Terbium", 158.93, "lanthanide", 9, 11, "Used in solid-state devices and green phosphors."),
    Element(66, "Dy", "Dysprosium", 162.50, "lanthanide", 9, 12, "Used in permanent magnets for electric motors."),
    Element(67, "Ho", "Holmium", 164.93, "lanthanide", 9, 13, "Has the highest magnetic strength of any element."),
    Element(68, "Er", "Erbium", 167.26, "lanthanide", 9, 14, "Used to amplify signals in fiber optic cables."),
    Element(69, "Tm", "Thulium", 168.93, "lanthanide", 9, 15, "Rarest naturally occurring lanthanide."),
    Element(70, "Yb", "Ytterbium", 173.05, "lanthanide", 9, 16, "Used in atomic clocks and portable X-ray devices."),
    Element(71, "Lu", "Lutetium", 174.97, "lanthanide", 9, 17, "Densest and hardest lanthanide."),
    Element(72, "Hf", "Hafnium", 178.49, "transition metal", 6, 4, "Used in nuclear control rods."),
    Element(73, "Ta", "Tantalum", 180.95, "transition metal", 6, 5, "Highly corrosion-resistant, used in electronics."),
    Element(74, "W", "Tungsten", 183.84, "transition metal", 6, 6, "Has the highest melting point of any metal."),
    Element(75, "Re", "Rhenium", 186.21, "transition metal", 6, 7, "One of the rarest elements in Earth's crust."),
    Element(76, "Os", "Osmium", 190.23, "transition metal", 6, 8, "Densest naturally occurring element."),
    Element(77, "Ir", "Iridium", 192.22, "transition metal", 6, 9, "Most corrosion-resistant metal known."),
    Element(78, "Pt", "Platinum", 195.08, "transition metal", 6, 10, "Precious metal used in jewelry and catalysts."),
    Element(79, "Au", "Gold", 196.97, "transition metal", 6, 11, "Precious metal prized for millennia, highly conductive."),
    Element(80, "Hg", "Mercury", 200.59, "transition metal", 6, 12, "Only metal that is liquid at room temperature."),
    Element(81, "Tl", "Thallium", 204.38, "post-transition metal", 6, 13, "Highly toxic, formerly used in rodenticides."),
    Element(82, "Pb", "Lead", 207.2, "post-transition metal", 6, 14, "Dense, soft metal historically used in pipes and paint."),
    Element(83, "Bi", "Bismuth", 208.98, "post-transition metal", 6, 15, "Least toxic heavy metal, used in cosmetics."),
    Element(84, "Po", "Polonium", 209.0, "post-transition metal", 6, 16, "Highly radioactive, discovered by Marie Curie."),
    Element(85, "At", "Astatine", 210.0, "reactive nonmetal", 6, 17, "Rarest naturally occurring element on Earth."),
    Element(86, "Rn", "Radon", 222.0, "noble gas", 6, 18, "Radioactive gas that can accumulate in basements."),
    Element(87, "Fr", "Francium", 223.0, "alkali metal", 7, 1, "One of the rarest and most unstable natural elements."),
    Element(88, "Ra", "Radium", 226.0, "alkaline earth metal", 7, 2, "Radioactive element once used in luminous paint."),
    Element(89, "Ac", "Actinium", 227.0, "actinide", 10, 3, "Glows blue in the dark due to radioactivity."),
    Element(90, "Th", "Thorium", 232.04, "actinide", 10, 4, "Potential nuclear fuel more abundant than uranium."),
    Element(91, "Pa", "Protactinium", 231.04, "actinide", 10, 5, "Rare, highly radioactive and toxic element."),
    Element(92, "U", "Uranium", 238.03, "actinide", 10, 6, "Fuel for nuclear reactors and weapons."),
    Element(93, "Np", "Neptunium", 237.0, "actinide", 10, 7, "First transuranium element discovered."),
    Element(94, "Pu", "Plutonium", 244.0, "actinide", 10, 8, "Used in nuclear weapons and space probe power sources."),
    Element(95, "Am", "Americium", 243.0, "actinide", 10, 9, "Used in household smoke detectors."),
    Element(96, "Cm", "Curium", 247.0, "actinide", 10, 10, "Named after Marie and Pierre Curie."),
    Element(97, "Bk", "Berkelium", 247.0, "actinide", 10, 11, "Synthetic element named after Berkeley, California."),
    Element(98, "Cf", "Californium", 251.0, "actinide", 10, 12, "Used as a neutron source for research."),
    Element(99, "Es", "Einsteinium", 252.0, "actinide", 10, 13, "Discovered in debris of the first hydrogen bomb test."),
    Element(100, "Fm", "Fermium", 257.0, "actinide", 10, 14, "Named after physicist Enrico Fermi."),
    Element(101, "Md", "Mendelevium", 258.0, "actinide", 10, 15, "Named after Dmitri Mendeleev, creator of the periodic table."),
    Element(102, "No", "Nobelium", 259.0, "actinide", 10, 16, "Named after Alfred Nobel."),
    Element(103, "Lr", "Lawrencium", 266.0, "actinide", 10, 17, "Named after physicist Ernest Lawrence."),
    Element(104, "Rf", "Rutherfordium", 267.0, "transition metal", 7, 4, "Synthetic superheavy element."),
    Element(105, "Db", "Dubnium", 268.0, "transition metal", 7, 5, "Named after Dubna, Russia."),
    Element(106, "Sg", "Seaborgium", 269.0, "transition metal", 7, 6, "Named after chemist Glenn T. Seaborg."),
    Element(107, "Bh", "Bohrium", 270.0, "transition metal", 7, 7, "Named after physicist Niels Bohr."),
    Element(108, "Hs", "Hassium", 269.0, "transition metal", 7, 8, "Named after the German state of Hesse."),
    Element(109, "Mt", "Meitnerium", 278.0, "unknown", 7, 9, "Named after physicist Lise Meitner."),
    Element(110, "Ds", "Darmstadtium", 281.0, "unknown", 7, 10, "Named after Darmstadt, Germany."),
    Element(111, "Rg", "Roentgenium", 282.0, "unknown", 7, 11, "Named after physicist Wilhelm Roentgen."),
    Element(112, "Cn", "Copernicium", 285.0, "transition metal", 7, 12, "Named after astronomer Nicolaus Copernicus."),
    Element(113, "Nh", "Nihonium", 286.0, "post-transition metal", 7, 13, "Named after Japan (Nihon), where it was discovered."),
    Element(114, "Fl", "Flerovium", 289.0, "post-transition metal", 7, 14, "Named after physicist Georgy Flyorov."),
    Element(115, "Mc", "Moscovium", 290.0, "post-transition metal", 7, 15, "Named after the Moscow region."),
    Element(116, "Lv", "Livermorium", 293.0, "post-transition metal", 7, 16, "Named after Lawrence Livermore National Laboratory."),
    Element(117, "Ts", "Tennessine", 294.0, "reactive nonmetal", 7, 17, "Named after the U.S. state of Tennessee."),
    Element(118, "Og", "Oganesson", 294.0, "noble gas", 7, 18, "Named after physicist Yuri Oganessian."),
]

ELEMENTS_BY_NUMBER: dict[int, Element] = {e.number: e for e in ELEMENTS}
