"""Static data for all 118 elements of the periodic table.

Grid coordinates (`period`, `group`) follow the standard 18-group layout,
with lanthanides and actinides placed on two separate rows below the main
body (periods 8 and 9 in this grid, groups 3-17).

Identity fields (number, symbol, name) and the grid layout (category, period,
group — period/group are synthetic grid coordinates, not real quantum
periods/groups, since lanthanides and actinides are placed on extra rows)
are hand-authored. Everything else, including mass and summary, is generated
by scripts/generate_data.py from the `mendeleev` package's data — regenerate
with `uv run python scripts/generate_data.py`.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class Element:
    number: int
    symbol: str
    name: str
    mass: float
    category: str
    period: int
    group: int
    summary: str
    melting_point: float | None  # kelvin
    boiling_point: float | None  # kelvin
    phase: str  # "solid", "liquid", "gas", or "unknown" at room temperature
    density: float | None  # g/cm^3
    electron_configuration: str
    electronegativity: float | None  # Pauling scale
    atomic_radius: float | None  # picometers
    oxidation_states: str


CATEGORY_COLORS: dict[str, str] = {
    "alkali metal": "#ff8a65",
    "alkaline earth metal": "#ffd54f",
    "transition metal": "#90caf9",
    "post-transition metal": "#a5d6a7",
    "metalloid": "#ce93d8",
    "reactive nonmetal": "#fff59d",
    "noble gas": "#80deea",
    "lanthanide": "#f48fb1",
    "actinide": "#ef9a9a",
    "unknown": "#bdbdbd",
}

ELEMENTS: list[Element] = [
    Element(number=1, symbol='H', name='Hydrogen', mass=1.008, category='reactive nonmetal', period=1, group=1, summary='Colourless, odourless gaseous chemical element. Lightest and most abundant element in the universe. Present in water and in all organic compounds. Chemically reacts with most elements. Discovered by Henry Cavendish in 1776.', melting_point=13.99, boiling_point=20.271, phase='gas', density=0.0001, electron_configuration='1s', electronegativity=2.2, atomic_radius=25.0, oxidation_states='+1, -1'),
    Element(number=2, symbol='He', name='Helium', mass=4.0026, category='noble gas', period=1, group=18, summary='Colourless, odourless gaseous nonmetallic element. Belongs to group 18 of the periodic table. Lowest boiling point of all elements and can only be solidified under pressure. Chemically inert, no known compounds. Discovered in the solar spectrum in 1868 by Lockyer.', melting_point=None, boiling_point=4.222, phase='gas', density=0.0002, electron_configuration='1s2', electronegativity=None, atomic_radius=120.0, oxidation_states=''),
    Element(number=3, symbol='Li', name='Lithium', mass=6.94, category='alkali metal', period=2, group=1, summary='Socket silvery metal. First member of group 1 of the periodic table. Lithium salts are used in psychomedicine.', melting_point=453.65, boiling_point=1615.15, phase='solid', density=0.534, electron_configuration='[He] 2s', electronegativity=0.98, atomic_radius=145.0, oxidation_states='+1'),
    Element(number=4, symbol='Be', name='Beryllium', mass=9.0122, category='alkaline earth metal', period=2, group=2, summary='Grey metallic element of group 2 of the periodic table. Is toxic and can cause severe lung diseases and dermatitis. Shows high covalent character. It was isolated independently by F. Wohler and A.A. Bussy in 1828.', melting_point=1560.15, boiling_point=2741.15, phase='solid', density=1.85, electron_configuration='[He] 2s2', electronegativity=1.57, atomic_radius=105.0, oxidation_states='+2'),
    Element(number=5, symbol='B', name='Boron', mass=10.81, category='metalloid', period=2, group=13, summary="An element of group 13 of the periodic table. There are two allotropes, amorphous boron is a brown power, but metallic boron is black. The metallic form is hard (9.3 on Mohs' scale) and a bad conductor in room temperatures. It is never found free in nature. Boron-10 is used in nuclear reactor control rods and shields. It was discovered in 1808 by Sir Humphry Davy and by J.L. Gay-Lussac and L.J. Thenard.", melting_point=2350.15, boiling_point=4273.15, phase='solid', density=2.34, electron_configuration='[He] 2s2 2p', electronegativity=2.04, atomic_radius=85.0, oxidation_states='+3'),
    Element(number=6, symbol='C', name='Carbon', mass=12.011, category='reactive nonmetal', period=2, group=14, summary='Carbon is a member of group 14 of the periodic table. It has three allotropic forms of it, diamonds, graphite and fullerite. Carbon-14 is commonly used in radioactive dating. Carbon occurs in all organic life and is the basis of organic chemistry. Carbon has the interesting chemical property of being able to bond with itself, and a wide variety of other elements.', melting_point=None, boiling_point=4098.15, phase='solid', density=2.2, electron_configuration='[He] 2s2 2p2', electronegativity=2.55, atomic_radius=70.0, oxidation_states='+4, -4'),
    Element(number=7, symbol='N', name='Nitrogen', mass=14.007, category='reactive nonmetal', period=2, group=15, summary='Colourless, gaseous element which belongs to group 15 of the periodic table. Constitutes ~78% of the atmosphere and is an essential part of the ecosystem. Nitrogen for industrial purposes is acquired by the fractional distillation of liquid air. Chemically inactive, reactive generally only at high temperatures or in electrical discharges. It was discovered in 1772 by D. Rutherford.', melting_point=63.15, boiling_point=77.355, phase='gas', density=0.0011, electron_configuration='[He] 2s2 2p3', electronegativity=3.04, atomic_radius=65.0, oxidation_states='+5, +3, -3'),
    Element(number=8, symbol='O', name='Oxygen', mass=15.999, category='reactive nonmetal', period=2, group=16, summary="A colourless, odourless gaseous element belonging to group 16 of the periodic table. It is the most abundant element present in the earth's crust. It also makes up 20.8% of the Earth's atmosphere. For industrial purposes, it is separated from liquid air by fractional distillation. It is used in high temperature welding, and in breathing. It commonly comes in the form of Oxygen, but is found as Ozone in the upper atmosphere. It was discovered by Priestley in 1774.", melting_point=54.36, boiling_point=90.188, phase='gas', density=0.0013, electron_configuration='[He] 2s2 2p4', electronegativity=3.44, atomic_radius=60.0, oxidation_states='-2'),
    Element(number=9, symbol='F', name='Fluorine', mass=18.9984, category='reactive nonmetal', period=2, group=17, summary='A poisonous pale yellow gaseous element belonging to group 17 of the periodic table (The halogens). It is the most chemically reactive and electronegative element. It is highly dangerous, causing severe chemical burns on contact with flesh. Fluorine was identified by Scheele in 1771 and first isolated by Moissan in 1886.', melting_point=53.48, boiling_point=85.04, phase='gas', density=0.0016, electron_configuration='[He] 2s2 2p5', electronegativity=3.98, atomic_radius=50.0, oxidation_states='-1'),
    Element(number=10, symbol='Ne', name='Neon', mass=20.1797, category='noble gas', period=2, group=18, summary='Colourless gaseous element of group 18 on the periodic table (noble gases). Neon occurs in the atmosphere, and comprises 0.0018% of the volume of the atmosphere. It has a distinct reddish glow when used in discharge tubes and neon based lamps. It forms almost no chemical compounds. Neon was discovered in 1898 by Sir William Ramsey and M.W. Travers.', melting_point=24.56, boiling_point=27.104, phase='gas', density=0.0008, electron_configuration='[He] 2s2 2p6', electronegativity=None, atomic_radius=160.0, oxidation_states=''),
    Element(number=11, symbol='Na', name='Sodium', mass=22.9898, category='alkali metal', period=3, group=1, summary='Soft silvery reactive element belonging to group 1 of the periodic table (alkali metals). It is highly reactive, oxidizing in air and reacting violently with water, forcing it to be kept under oil. It was first isolated by Humphrey Davy in 1807.', melting_point=370.944, boiling_point=1156.09, phase='solid', density=0.97, electron_configuration='[Ne] 3s', electronegativity=0.93, atomic_radius=180.0, oxidation_states='+1'),
    Element(number=12, symbol='Mg', name='Magnesium', mass=24.305, category='alkaline earth metal', period=3, group=2, summary='Silvery metallic element belonging to group 2 of the periodic table (alkaline-earth metals). It is essential for living organisms, and is used in a number of light alloys. Chemically very reactive, it forms a protective oxide coating when exposed to air and burns with an intense white flame. It also reacts with sulphur, nitrogen and the halogens. First isolated by Bussy in 1828.', melting_point=923.15, boiling_point=1363.15, phase='solid', density=1.74, electron_configuration='[Ne] 3s2', electronegativity=1.31, atomic_radius=150.0, oxidation_states='+2'),
    Element(number=13, symbol='Al', name='Aluminium', mass=26.9815, category='post-transition metal', period=3, group=13, summary="Silvery-white lustrous metallic element of group 3 of the periodic table. Highly reactive but protected by a thin transparent layer of the oxide which quickly forms in air. There are many alloys of aluminum, as well as a good number of industrial uses. Makes up 8.1% of the Earth's crust, by weight. Isolated in 1825 by H.C. Oersted.", melting_point=933.473, boiling_point=2792.15, phase='solid', density=2.7, electron_configuration='[Ne] 3s2 3p', electronegativity=1.61, atomic_radius=125.0, oxidation_states='+3'),
    Element(number=14, symbol='Si', name='Silicon', mass=28.085, category='metalloid', period=3, group=14, summary="Metalloid element belonging to group 14 of the periodic table. It is the second most abundant element in the Earth's crust, making up 25.7% of it by weight. Chemically less reactive than carbon. First identified by Lavoisier in 1787 and first isolated in 1823 by Berzelius.", melting_point=1687.15, boiling_point=3538.15, phase='solid', density=2.3296, electron_configuration='[Ne] 3s2 3p2', electronegativity=1.9, atomic_radius=110.0, oxidation_states='+4, -4'),
    Element(number=15, symbol='P', name='Phosphorus', mass=30.9738, category='reactive nonmetal', period=3, group=15, summary='Non-metallic element belonging to group 15 of the periodic table. Has a multiple allotropic forms. Essential element for living organisms. It was discovered by Brandt in 1669.', melting_point=317.3, boiling_point=553.65, phase='solid', density=1.823, electron_configuration='[Ne] 3s2 3p3', electronegativity=2.19, atomic_radius=100.0, oxidation_states='+5, +3, -3'),
    Element(number=16, symbol='S', name='Sulfur', mass=32.06, category='reactive nonmetal', period=3, group=16, summary='Yellow, nonmetallic element belonging to group 16 of the periodic table. It is an essential element in living organisms, needed in the amino acids cysteine and methionine, and hence in many proteins. Absorbed by plants from the soil as sulphate ion.', melting_point=368.35, boiling_point=717.76, phase='solid', density=2.07, electron_configuration='[Ne] 3s2 3p4', electronegativity=2.58, atomic_radius=100.0, oxidation_states='+6, +4, +2, -2'),
    Element(number=17, symbol='Cl', name='Chlorine', mass=35.45, category='reactive nonmetal', period=3, group=17, summary='Halogen element. Poisonous greenish-yellow gas. Occurs widely in nature as sodium chloride in seawater. Reacts directly with many elements and compounds, strong oxidizing agent. Discovered by Karl Scheele in 1774. Humphrey David confirmed it as an element in 1810.', melting_point=171.65, boiling_point=239.11, phase='gas', density=0.0029, electron_configuration='[Ne] 3s2 3p5', electronegativity=3.16, atomic_radius=100.0, oxidation_states='+7, +5, +3, +1, -1'),
    Element(number=18, symbol='Ar', name='Argon', mass=39.948, category='noble gas', period=3, group=18, summary='Monatomic noble gas. Makes up 0.93% of the air. Colourless, odorless. Is inert and has no true compounds. Lord Rayleigh and Sir william Ramsey identified argon in 1894.', melting_point=83.81, boiling_point=87.302, phase='gas', density=0.0016, electron_configuration='[Ne] 3s2 3p6', electronegativity=None, atomic_radius=71.0, oxidation_states=''),
    Element(number=19, symbol='K', name='Potassium', mass=39.0983, category='alkali metal', period=4, group=1, summary='Soft silvery metallic element belonging to group 1 of the periodic table (alkali metals). Occurs naturally in seawater and a many minerals. Highly reactive, chemically, it resembles sodium in its behavior and compounds. Discovered by Sir Humphry Davy in 1807.', melting_point=336.65, boiling_point=1032.15, phase='solid', density=0.89, electron_configuration='[Ar] 4s', electronegativity=0.82, atomic_radius=220.0, oxidation_states='+1'),
    Element(number=20, symbol='Ca', name='Calcium', mass=40.078, category='alkaline earth metal', period=4, group=2, summary='Soft grey metallic element belonging to group 2 of the periodic table. Used a reducing agent in the extraction of thorium, zirconium and uranium. Essential element for living organisms.', melting_point=1115.15, boiling_point=1757.15, phase='solid', density=1.54, electron_configuration='[Ar] 4s2', electronegativity=1.0, atomic_radius=180.0, oxidation_states='+2'),
    Element(number=21, symbol='Sc', name='Scandium', mass=44.9559, category='transition metal', period=4, group=3, summary='Rare soft silvery metallic element belonging to group 3 of the periodic table. There are ten isotopes, nine of which are radioactive and have short half-lives. Predicted in 1869 by Mendeleev, isolated by Nilson in 1879.', melting_point=1814.15, boiling_point=3109.15, phase='solid', density=2.99, electron_configuration='[Ar] 3d 4s2', electronegativity=1.36, atomic_radius=160.0, oxidation_states='+3'),
    Element(number=22, symbol='Ti', name='Titanium', mass=47.867, category='transition metal', period=4, group=4, summary='White metallic transition element. Occurs in numerous minerals. Used in strong, light corrosion-resistant alloys. Forms a passive oxide coating when exposed to air. First discovered by Gregor in 1789.', melting_point=1943.15, boiling_point=3560.15, phase='solid', density=4.506, electron_configuration='[Ar] 3d2 4s2', electronegativity=1.54, atomic_radius=140.0, oxidation_states='+4'),
    Element(number=23, symbol='V', name='Vanadium', mass=50.9415, category='transition metal', period=4, group=5, summary='Soft and ductile, bright white metal. Good resistance to corrosion by alkalis, sulphuric and hydrochloric acid. It oxidizes readily about 933K. There are two naturally occurring isotopes of vanadium, and 5 radioisotopes, V-49 having the longest half-life at 337 days. Vanadium has nuclear applications, the foil is used in cladding titanium to steel, and vanadium-gallium tape is used to produce a superconductive magnet. Originally discovered by Andres Manuel del Rio of Mexico City in 1801. His discovery went unheeded, however, and in 1820, Nils Gabriel Sefstron of Sweden rediscovered it. Metallic vanadium was isolated by Henry Enfield Roscoe in 1867. The name vanadium comes from Vanadis, a goddess of Scandinavian mythology. Silvery-white metallic transition element. Vanadium is essential to Ascidians. Rats and chickens are also known to require it. Metal powder is a fire hazard, and vanadium compounds should be considered highly toxic. May cause lung cancer if inhaled.', melting_point=2183.15, boiling_point=3680.15, phase='solid', density=6.0, electron_configuration='[Ar] 3d3 4s2', electronegativity=1.63, atomic_radius=135.0, oxidation_states='+5'),
    Element(number=24, symbol='Cr', name='Chromium', mass=51.9961, category='transition metal', period=4, group=6, summary='Hard silvery transition element. Used in decorative electroplating. Discovered in 1797 by Vauquelin.', melting_point=2180.15, boiling_point=2944.15, phase='solid', density=7.15, electron_configuration='[Ar] 3d5 4s', electronegativity=1.66, atomic_radius=140.0, oxidation_states='+6, +3'),
    Element(number=25, symbol='Mn', name='Manganese', mass=54.938, category='transition metal', period=4, group=7, summary='Grey brittle metallic transition element. Rather electropositive, combines with some non-metals when heated. Discovered in 1774 by Scheele.', melting_point=1519.15, boiling_point=2334.15, phase='solid', density=7.3, electron_configuration='[Ar] 3d5 4s2', electronegativity=1.55, atomic_radius=140.0, oxidation_states='+7, +4, +2'),
    Element(number=26, symbol='Fe', name='Iron', mass=55.845, category='transition metal', period=4, group=8, summary="Silvery malleable and ductile metallic transition element. Has nine isotopes and is the fourth most abundant element in the earth's crust. Required by living organisms as a trace element (used in hemoglobin in humans.) Quite reactive, oxidizes in moist air, displaces hydrogen from dilute acids and combines with nonmetallic elements.", melting_point=1811.15, boiling_point=3134.15, phase='solid', density=7.87, electron_configuration='[Ar] 3d6 4s2', electronegativity=1.83, atomic_radius=140.0, oxidation_states='+3, +2'),
    Element(number=27, symbol='Co', name='Cobalt', mass=58.9332, category='transition metal', period=4, group=9, summary='Light grey transition element. Some meteorites contain small amounts of metallic cobalt. Generally alloyed for use. Mammals require small amounts of cobalt salts. Cobalt-60, an artificially produced radioactive isotope of Cobalt is an important radioactive tracer and cancer-treatment agent. Discovered by G. Brandt in 1737.', melting_point=1768.15, boiling_point=3200.15, phase='solid', density=8.86, electron_configuration='[Ar] 3d7 4s2', electronegativity=1.88, atomic_radius=135.0, oxidation_states='+3, +2'),
    Element(number=28, symbol='Ni', name='Nickel', mass=58.6934, category='transition metal', period=4, group=10, summary='Malleable ductile silvery metallic transition element. Discovered by A.F. Cronstedt in 1751.', melting_point=1728.15, boiling_point=3186.15, phase='solid', density=8.9, electron_configuration='[Ar] 3d8 4s2', electronegativity=1.91, atomic_radius=135.0, oxidation_states='+2'),
    Element(number=29, symbol='Cu', name='Copper', mass=63.546, category='transition metal', period=4, group=11, summary="Red-brown transition element. Known by the Romans as 'cuprum.' Extracted and used for thousands of years. Malleable, ductile and an excellent conductor of heat and electricity. When in moist conditions, a greenish layer forms on the outside.", melting_point=1357.77, boiling_point=2833.15, phase='solid', density=8.96, electron_configuration='[Ar] 3d10 4s', electronegativity=1.9, atomic_radius=135.0, oxidation_states='+2'),
    Element(number=30, symbol='Zn', name='Zinc', mass=65.38, category='transition metal', period=4, group=12, summary='Blue-white metallic element. Occurs in multiple compounds naturally. Five stable isotopes are six radioactive isotopes have been found. Chemically a reactive metal, combines with oxygen and other non-metals, reacts with dilute acids to release hydrogen.', melting_point=692.677, boiling_point=1180.15, phase='solid', density=7.134, electron_configuration='[Ar] 3d10 4s2', electronegativity=1.65, atomic_radius=135.0, oxidation_states='+2'),
    Element(number=31, symbol='Ga', name='Gallium', mass=69.723, category='post-transition metal', period=4, group=13, summary='Soft silvery metallic element, belongs to group 13 of the periodic table. The two stable isotopes are Ga-69 and Ga-71. Eight radioactive isotopes are known, all having short half-lives. Gallium Arsenide is used as a semiconductor. Corrodes most other metals by diffusing into their lattice. First identified by Francois Lecoq de Boisbaudran in 1875.', melting_point=302.9146, boiling_point=2502.15, phase='solid', density=5.91, electron_configuration='[Ar] 3d10 4s2 4p', electronegativity=1.81, atomic_radius=130.0, oxidation_states='+3'),
    Element(number=32, symbol='Ge', name='Germanium', mass=72.63, category='metalloid', period=4, group=14, summary='Lustrous hard metalloid element, belongs to group 14 of the periodic table. Forms a large number of organometallic compounds. Predicted by Mendeleev in 1871, it was actually found in 1886 by Winkler.', melting_point=1211.4, boiling_point=3106.15, phase='solid', density=5.3234, electron_configuration='[Ar] 3d10 4s2 4p2', electronegativity=2.01, atomic_radius=125.0, oxidation_states='+4, +2, -4'),
    Element(number=33, symbol='As', name='Arsenic', mass=74.9216, category='metalloid', period=4, group=15, summary='Metalloid element of group 15. There are three allotropes, yellow, black, and grey. Reacts with halogens, concentrated oxidizing acids and hot alkalis. Albertus Magnus is believed to have been the first to isolate the element in 1250.', melting_point=1090.15, boiling_point=889.15, phase='solid', density=5.75, electron_configuration='[Ar] 3d10 4s2 4p3', electronegativity=2.18, atomic_radius=115.0, oxidation_states='+5, +3, -3'),
    Element(number=34, symbol='Se', name='Selenium', mass=78.971, category='reactive nonmetal', period=4, group=16, summary='Metalloid element, belongs to group 16 of the periodic table. Multiple allotropic forms exist. Chemically resembles sulphur. Discovered in 1817 by Jons J. Berzelius.', melting_point=453.15, boiling_point=958.15, phase='solid', density=4.809, electron_configuration='[Ar] 3d10 4s2 4p4', electronegativity=2.55, atomic_radius=115.0, oxidation_states='+6, +4, +2, -2'),
    Element(number=35, symbol='Br', name='Bromine', mass=79.904, category='reactive nonmetal', period=4, group=17, summary='Halogen element. Red volatile liquid at room temperature. Its reactivity is somewhere between chlorine and iodine. Harmful to human tissue in a liquid state, the vapour irritates eyes and throat. Discovered in 1826 by Antoine Balard.', melting_point=265.95, boiling_point=331.95, phase='liquid', density=3.1028, electron_configuration='[Ar] 3d10 4s2 4p5', electronegativity=2.96, atomic_radius=115.0, oxidation_states='+5, +3, +1, -1'),
    Element(number=36, symbol='Kr', name='Krypton', mass=83.798, category='noble gas', period=4, group=18, summary='Colorless gaseous element, belongs to the noble gases. Occurs in the air, 0.0001% by volume. It can be extracted from liquid air by fractional distillation. Generally not isolated, but used with other inert gases in fluorescent lamps. Five natural isotopes, and five radioactive isotopes. Kr-85, the most stable radioactive isotope, has a half-life of 10.76 years and is produced in fission reactors. Practically inert, though known to form compounds with Fluorine.', melting_point=115.78, boiling_point=119.735, phase='gas', density=0.0034, electron_configuration='[Ar] 3d10 4s2 4p6', electronegativity=None, atomic_radius=None, oxidation_states='+2'),
    Element(number=37, symbol='Rb', name='Rubidium', mass=85.4678, category='alkali metal', period=5, group=1, summary='Soft silvery metallic element, belongs to group 1 of the periodic table. Rb-97, the naturally occurring isotope, is radioactive. It is highly reactive, with properties similar to other elements in group 1, like igniting spontaneously in air. Discovered spectroscopically in 1861 by W. Bunsen and G.R. Kirchoff.', melting_point=312.45, boiling_point=961.15, phase='solid', density=1.53, electron_configuration='[Kr] 5s', electronegativity=0.82, atomic_radius=235.0, oxidation_states='+1'),
    Element(number=38, symbol='Sr', name='Strontium', mass=87.62, category='alkaline earth metal', period=5, group=2, summary='Soft yellowish metallic element, belongs to group 2 of the periodic table. Highly reactive chemically. Sr-90 is present in radioactive fallout and has a half-life of 28 years. Discovered in 1798 by Klaproth and Hope, isolated in 1808 by Humphry Davy.', melting_point=1050.15, boiling_point=1650.15, phase='solid', density=2.64, electron_configuration='[Kr] 5s2', electronegativity=0.95, atomic_radius=200.0, oxidation_states='+2'),
    Element(number=39, symbol='Y', name='Yttrium', mass=88.9058, category='transition metal', period=5, group=3, summary='Silvery-grey metallic element of group 3 on the periodic table. Found in uranium ores. The only natural isotope is Y-89, there are 14 other artificial isotopes. Chemically resembles the lanthanoids. Stable in the air below 400 degrees, celsius. Discovered in 1828 by Friedrich Wohler.', melting_point=1795.15, boiling_point=3618.15, phase='solid', density=4.47, electron_configuration='[Kr] 4d 5s2', electronegativity=1.22, atomic_radius=180.0, oxidation_states='+3'),
    Element(number=40, symbol='Zr', name='Zirconium', mass=91.224, category='transition metal', period=5, group=4, summary='Grey-white metallic transition element. Five natural isotopes and six radioactive isotopes are known. Used in nuclear reactors for a Neutron absorber. Discovered in 1789 by Martin Klaproth, isolated in 1824 by Berzelius.', melting_point=2127.15, boiling_point=4679.15, phase='solid', density=6.52, electron_configuration='[Kr] 4d2 5s2', electronegativity=1.33, atomic_radius=155.0, oxidation_states='+4'),
    Element(number=41, symbol='Nb', name='Niobium', mass=92.9064, category='transition metal', period=5, group=5, summary='Soft, ductile grey-blue metallic transition element. Used in special steels and in welded joints to increase strength. Combines with halogens and oxidizes in air at 200 degrees celsius. Discovered by Charles Hatchett in 1801 and isolated by Blomstrand in 1864. Called Columbium originally.', melting_point=2750.15, boiling_point=5014.15, phase='solid', density=8.57, electron_configuration='[Kr] 4d4 5s', electronegativity=1.6, atomic_radius=145.0, oxidation_states='+5'),
    Element(number=42, symbol='Mo', name='Molybdenum', mass=95.95, category='transition metal', period=5, group=6, summary='Silvery-white, hard metallic transition element. It is chemically unreactive and is not affected by most acids. It oxidizes at high temperatures. There are seven natural isotopes, and four radioisotopes, Mo-93 being the most stable with a half-life of 3500 years. Molybdenum is used in almost all high-strength steels, it has nuclear applications, and is a catalyst in petroleum refining. Discovered in 1778 by Carl Welhelm Scheele of Sweden. Impure metal was prepared in 1782 by Peter Jacob Hjelm. The name comes from the Greek word molybdos which means lead. Trace amounts of molybdenum are required for all known forms of life. All molybdenum compounds should be considered highly toxic, and will also cause severe birth defects.', melting_point=2895.15, boiling_point=4912.15, phase='solid', density=10.2, electron_configuration='[Kr] 4d5 5s', electronegativity=2.16, atomic_radius=145.0, oxidation_states='+6, +4'),
    Element(number=43, symbol='Tc', name='Technetium', mass=97.9072, category='transition metal', period=5, group=7, summary='Radioactive metallic transition element. Can be detected in some stars and the fission products of uranium. First made by Perrier and Segre by bombarding molybdenum with deutrons, giving them Tc-97. Tc-99 is the most stable isotope with a half-life of 2.6*10^6 years. Sixteen isotopes are known. Organic technetium compounds are used in bone imaging. Chemical properties are intermediate between rhenium and manganese.', melting_point=2430.15, boiling_point=4535.15, phase='solid', density=11.0, electron_configuration='[Kr] 4d5 5s2', electronegativity=2.1, atomic_radius=135.0, oxidation_states='+7, +4'),
    Element(number=44, symbol='Ru', name='Ruthenium', mass=101.07, category='transition metal', period=5, group=8, summary='Hard white metallic transition element. Found with platinum, used as a catalyst in some platinum alloys. Dissolves in fused alkalis, and is not attacked by acids. Reacts with halogens and oxygen at high temperatures. Isolated in 1844 by K.K. Klaus.', melting_point=2606.15, boiling_point=4420.15, phase='solid', density=12.1, electron_configuration='[Kr] 4d7 5s', electronegativity=2.2, atomic_radius=130.0, oxidation_states='+4, +3'),
    Element(number=45, symbol='Rh', name='Rhodium', mass=102.9055, category='transition metal', period=5, group=9, summary='Silvery white metallic transition element. Found with platinum and used in some platinum alloys. Not attacked by acids, dissolves only in aqua regia. Discovered in 1803 by W.H. Wollaston.', melting_point=2236.15, boiling_point=3968.15, phase='solid', density=12.4, electron_configuration='[Kr] 4d8 5s', electronegativity=2.28, atomic_radius=135.0, oxidation_states='+3'),
    Element(number=46, symbol='Pd', name='Palladium', mass=106.42, category='transition metal', period=5, group=10, summary='Soft white ductile transition element. Found with some copper and nickel ores. Does not react with oxygen at normal temperatures. Dissolves slowly in hydrochloric acid. Discovered in 1803 by W.H. Wollaston.', melting_point=1827.95, boiling_point=3236.15, phase='solid', density=12.0, electron_configuration='[Kr] 4d10', electronegativity=2.2, atomic_radius=140.0, oxidation_states='+4, +2'),
    Element(number=47, symbol='Ag', name='Silver', mass=107.8682, category='transition metal', period=5, group=11, summary='White lustrous soft metallic transition element. Found in both its elemental form and in minerals. Used in jewellery, tableware and so on. Less reactive than silver, chemically.', melting_point=1234.93, boiling_point=2435.15, phase='solid', density=10.5, electron_configuration='[Kr] 4d10 5s', electronegativity=1.93, atomic_radius=160.0, oxidation_states='+1'),
    Element(number=48, symbol='Cd', name='Cadmium', mass=112.414, category='transition metal', period=5, group=12, summary='Soft bluish metal belonging to group 12 of the periodic table. Extremely toxic even in low concentrations. Chemically similar to zinc, but lends itself to more complex compounds. Discovered in 1817 by F. Stromeyer.', melting_point=594.219, boiling_point=1040.15, phase='solid', density=8.69, electron_configuration='[Kr] 4d10 5s2', electronegativity=1.69, atomic_radius=155.0, oxidation_states='+2'),
    Element(number=49, symbol='In', name='Indium', mass=114.818, category='post-transition metal', period=5, group=13, summary='Soft silvery element belonging to group 13 of the periodic table. The most common natural isotope is In-115, which has a half-life of 6*10^4 years. Five other radioisotopes exist. Discovered in 1863 by Reich and Richter.', melting_point=429.7485, boiling_point=2300.15, phase='solid', density=7.31, electron_configuration='[Kr] 4d10 5s2 5p', electronegativity=1.78, atomic_radius=155.0, oxidation_states='+3'),
    Element(number=50, symbol='Sn', name='Tin', mass=118.71, category='post-transition metal', period=5, group=14, summary='Silvery malleable metallic element belonging to group 14 of the periodic table. Twenty-six isotopes are known, five of which are radioactive. Chemically reactive. Combines directly with chlorine and oxygen and displaces hydrogen from dilute acids.', melting_point=286.35, boiling_point=2859.15, phase='liquid', density=7.287, electron_configuration='[Kr] 4d10 5s2 5p2', electronegativity=1.96, atomic_radius=145.0, oxidation_states='+4, +2, -4'),
    Element(number=51, symbol='Sb', name='Antimony', mass=121.76, category='metalloid', period=5, group=15, summary='Element of group 15. Multiple allotropic forms. The stable form of antimony is a blue-white metal. Yellow and black antimony are unstable non-metals. Used in flame-proofing, paints, ceramics, enamels, and rubber. Attacked by oxidizing acids and halogens. First reported by Tholden in 1450.', melting_point=903.778, boiling_point=1860.15, phase='solid', density=6.68, electron_configuration='[Kr] 4d10 5s2 5p3', electronegativity=2.05, atomic_radius=145.0, oxidation_states='+5, +3, -3'),
    Element(number=52, symbol='Te', name='Tellurium', mass=127.6, category='metalloid', period=5, group=16, summary='Silvery metalloid element of group 16. Eight natural isotopes, nine radioactive isotopes. Used in semiconductors and to a degree in some steels. Chemistry is similar to Sulphur. Discovered in 1782 by Franz Miller.', melting_point=722.66, boiling_point=1261.15, phase='solid', density=6.232, electron_configuration='[Kr] 4d10 5s2 5p4', electronegativity=2.1, atomic_radius=140.0, oxidation_states='+6, +4, +2, -2'),
    Element(number=53, symbol='I', name='Iodine', mass=126.9045, category='reactive nonmetal', period=5, group=17, summary='Dark violet nonmetallic element, belongs to group 17 of the periodic table. Insoluble in water. Required as a trace element for living organisms. One stable isotope, I-127 exists, in addition to fourteen radioactive isotopes. Chemically the least reactive of the halogens, and the most electropositive metallic halogen. Discovered in 1812 by Courtois.', melting_point=386.85, boiling_point=457.55, phase='solid', density=4.933, electron_configuration='[Kr] 4d10 5s2 5p5', electronegativity=2.66, atomic_radius=140.0, oxidation_states='+7, +5, +3, +1, -1'),
    Element(number=54, symbol='Xe', name='Xenon', mass=131.293, category='noble gas', period=5, group=18, summary='Colourless, odourless gas belonging to group 18 on the periodic table (the noble gases.) Nine natural isotopes and seven radioactive isotopes are known. Xenon was part of the first noble-gas compound synthesized. Several others involving Xenon have been found since then. Xenon was discovered by Ramsey and Travers in 1898.', melting_point=161.4, boiling_point=165.051, phase='gas', density=0.0054, electron_configuration='[Kr] 4d10 5s2 5p6', electronegativity=2.6, atomic_radius=None, oxidation_states='+6, +4, +2'),
    Element(number=55, symbol='Cs', name='Caesium', mass=132.9055, category='alkali metal', period=6, group=1, summary='Soft silvery-white metallic element belonging to group 1 of the periodic table. One of the three metals which are liquid at room temperature. Cs-133 is the natural, and only stable, isotope. Fifteen other radioisotopes exist. Caesium reacts explosively with cold water, and ice at temperatures above 157K. Caesium hydroxide is the strongest base known. Caesium is the most electropositive, most alkaline and has the least ionization potential of all the elements. Known uses include the basis of atomic clocks, catalyst for the hydrogenation of some organic compounds, and in photoelectric cells. Caesium was discovered by Gustav Kirchoff and Robert Bunsen in Germany in 1860 spectroscopically. Its identification was based upon the bright blue lines in its spectrum. The name comes from the latin word caesius, which means sky blue. Caesium should be considered highly toxic. Some of the radioisotopes are even more toxic.', melting_point=301.65, boiling_point=944.15, phase='solid', density=1.873, electron_configuration='[Xe] 6s', electronegativity=0.79, atomic_radius=260.0, oxidation_states='+1'),
    Element(number=56, symbol='Ba', name='Barium', mass=137.327, category='alkaline earth metal', period=6, group=2, summary='Silvery-white reactive element, belonging to group 2 of the periodic table. Soluble barium compounds are extremely poisonous. Identified in 1774 by Karl Scheele and extracted in 1808 by Humphry Davy.', melting_point=1000.15, boiling_point=2118.15, phase='solid', density=3.62, electron_configuration='[Xe] 6s2', electronegativity=0.89, atomic_radius=215.0, oxidation_states='+2'),
    Element(number=57, symbol='La', name='Lanthanum', mass=138.9055, category='lanthanide', period=9, group=3, summary='(From the Greek word lanthanein, to line hidden) Silvery metallic element belonging to group 3 of the periodic table and oft considered to be one of the lanthanoids. Found in some rare-earth minerals. Twenty-five natural isotopes exist. La-139 which is stable, and La-138 which has a half-life of 10^10 to 10^15 years. The other twenty-three isotopes are radioactive. It resembles the lanthanoids chemically. Lanthanum has a low to moderate level of toxicity, and should be handled with care. Discovered in 1839 by C.G. Mosander.', melting_point=1193.15, boiling_point=3737.15, phase='solid', density=6.15, electron_configuration='[Xe] 5d 6s2', electronegativity=1.1, atomic_radius=195.0, oxidation_states='+3'),
    Element(number=58, symbol='Ce', name='Cerium', mass=140.116, category='lanthanide', period=9, group=4, summary='Silvery metallic element, belongs to the lanthanoids. Four natural isotopes exist, and fifteen radioactive isotopes have been identified. Used in some rare-earth alloys. The oxidized form is used in the glass industry. Discovered by Martin .H. Klaproth in 1803.', melting_point=1072.15, boiling_point=3716.15, phase='solid', density=6.77, electron_configuration='[Xe] 4f 5d 6s2', electronegativity=1.12, atomic_radius=185.0, oxidation_states='+4, +3'),
    Element(number=59, symbol='Pr', name='Praseodymium', mass=140.9077, category='lanthanide', period=9, group=5, summary='Soft silvery metallic element, belongs to the lanthanoids. Only natural isotope is Pr-141 which is not radioactive. Fourteen radioactive isotopes have been artificially produced. Used in rare-earth alloys. Discovered in 1885 by C.A. von Welsbach.', melting_point=1204.15, boiling_point=3793.15, phase='solid', density=6.773, electron_configuration='[Xe] 4f3 6s2', electronegativity=1.13, atomic_radius=185.0, oxidation_states='+3'),
    Element(number=60, symbol='Nd', name='Neodymium', mass=144.242, category='lanthanide', period=9, group=6, summary="Soft bright silvery metallic element, belongs to the lanthanoids. Seven natural isotopes, Nd-144 being the only radioactive one with a half-life of 10^10 to 10^15 years. Six artificial radioisotopes have been produced. The metal is used in glass works to color class a shade of violet-purple and make it dichroic. One of the more reactive rare-earth metals, quickly reacts with air. Used in some rare-earth alloys. Neodymium is used to color the glass used in welder's glasses. Neodymium is also used in very powerful, permanent magnets (Nd2Fe14B). Discovered by Carl F. Auer von Welsbach in Austria in 1885 by separating didymium into its elemental components Praseodymium and neodymium. The name comes from the Greek words 'neos didymos' which means 'new twin'. Neodymium should be considered highly toxic, however evidence would seem to show that it acts as little more than a skin and eye irritant. The dust however, presents a fire and explosion hazard.", melting_point=1289.15, boiling_point=3347.15, phase='solid', density=7.01, electron_configuration='[Xe] 4f4 6s2', electronegativity=1.14, atomic_radius=185.0, oxidation_states='+3'),
    Element(number=61, symbol='Pm', name='Promethium', mass=144.9128, category='lanthanide', period=9, group=7, summary='Soft silvery metallic element, belongs to the lanthanoids. Pm-147, the only natural isotope, is radioactive and has a half-life of 252 years. Eighteen radioisotopes have been produced, but all have very short half-lives. Found only in nuclear decay waste. Pm-147 is of interest as a beta-decay source, however Pm-146 and Pm-148 have to be removed from it first, as they generate gamma radiation. Discovered by J.A. Marinsky, L.E. Glendenin and C.D. Coryell in 1947.', melting_point=1315.15, boiling_point=None, phase='solid', density=7.26, electron_configuration='[Xe] 4f5 6s2', electronegativity=None, atomic_radius=185.0, oxidation_states='+3'),
    Element(number=62, symbol='Sm', name='Samarium', mass=150.36, category='lanthanide', period=9, group=8, summary='Soft silvery metallic element, belongs to the lanthanoids. Seven natural isotopes, Sm-147 is the only radioisotope, and has a half-life of 2.5*10^11 years. Used for making special alloys needed in the production of nuclear reactors. Also used as a neutron absorber. Small quantities of samarium oxide is used in special optical glasses. The largest use of the element is its ferromagnetic alloy which produces permanent magnets that are five times stronger than magnets produced by any other material. Discovered by Francois Lecoq de Boisbaudran in 1879.', melting_point=1345.15, boiling_point=2067.15, phase='solid', density=7.52, electron_configuration='[Xe] 4f6 6s2', electronegativity=1.17, atomic_radius=185.0, oxidation_states='+3'),
    Element(number=63, symbol='Eu', name='Europium', mass=151.964, category='lanthanide', period=9, group=9, summary='Soft silvery metallic element belonging to the lanthanoids. Eu-151 and Eu-153 are the only two stable isotopes, both of which are Neutron absorbers. Discovered in 1889 by Sir William Crookes.', melting_point=1095.15, boiling_point=1802.15, phase='solid', density=5.24, electron_configuration='[Xe] 4f7 6s2', electronegativity=None, atomic_radius=185.0, oxidation_states='+3, +2'),
    Element(number=64, symbol='Gd', name='Gadolinium', mass=157.25, category='lanthanide', period=9, group=10, summary='Soft silvery metallic element belonging to the lanthanoids. Seven natural, stable isotopes are known in addition to eleven artificial isotopes. Gd-155 and Gd-157 and the best neutron absorbers of all elements. Gadolinium compounds are used in electronics. Discovered by J.C.G Marignac in 1880.', melting_point=1586.15, boiling_point=3546.15, phase='solid', density=7.9, electron_configuration='[Xe] 4f7 5d 6s2', electronegativity=1.2, atomic_radius=180.0, oxidation_states='+3'),
    Element(number=65, symbol='Tb', name='Terbium', mass=158.9254, category='lanthanide', period=9, group=11, summary='Silvery metallic element belonging to the lanthanoids. Tb-159 is the only stable isotope, there are seventeen artificial isotopes. Discovered by G.G. Mosander in 1843.', melting_point=1632.15, boiling_point=3503.15, phase='solid', density=8.23, electron_configuration='[Xe] 4f9 6s2', electronegativity=None, atomic_radius=175.0, oxidation_states='+3'),
    Element(number=66, symbol='Dy', name='Dysprosium', mass=162.5, category='lanthanide', period=9, group=12, summary='Metallic with a bright silvery-white lustre. Dysprosium belongs to the lanthanoids. It is relatively stable in air at room temperatures, it will however dissolve in mineral acids, evolving hydrogen. It is found in from rare-earth minerals. There are seven natural isotopes of dysprosium, and eight radioisotopes, Dy-154 being the most stable with a half-life of 3*10^6 years. Dysprosium is used as a neutron absorber in nuclear fission reactions, and in compact disks. It was discovered by Paul Emile Lecoq de Boisbaudran in 1886 in France. Its name comes from the Greek word dysprositos, which means hard to obtain.', melting_point=1685.15, boiling_point=2840.15, phase='solid', density=8.55, electron_configuration='[Xe] 4f10 6s2', electronegativity=1.22, atomic_radius=175.0, oxidation_states='+3'),
    Element(number=67, symbol='Ho', name='Holmium', mass=164.9303, category='lanthanide', period=9, group=13, summary="Relatively soft and malleable silvery-white metallic element, which is stable in dry air at room temperature. It oxidizes in moist air and at high temperatures. It belongs to the lanthanoids. A rare-earth metal, it is found in the minerals monazite and gadolinite. It possesses unusual magnetic properties. One natural isotope, Ho-165 exists, six radioisotopes exist, the most stable being Ho-163 with a half-life of 4570 years. Holmium is used in some metal alloys, it is also said to stimulate the metabolism. Discovered by Per Theodor Cleve and J.L. Soret in Switzerland in 1879. The name homium comes from the Greek word Holmia which means Sweden. While all holmium compounds should be considered highly toxic, initial evidence seems to indicate that they do not pose much danger. The metal's dust however, is a fire hazard.", melting_point=1745.15, boiling_point=2973.15, phase='solid', density=8.8, electron_configuration='[Xe] 4f11 6s2', electronegativity=1.23, atomic_radius=175.0, oxidation_states='+3'),
    Element(number=68, symbol='Er', name='Erbium', mass=167.259, category='lanthanide', period=9, group=14, summary='Soft silvery metallic element which belongs to the lanthanoids. Six natural isotopes that are stable. Twelve artificial isotopes are known. Used in nuclear technology as a neutron absorber. It is being investigated for other possible uses. Discovered by Carl G. Mosander in 1843.', melting_point=1802.15, boiling_point=3141.15, phase='solid', density=9.07, electron_configuration='[Xe] 4f12 6s2', electronegativity=1.24, atomic_radius=175.0, oxidation_states='+3'),
    Element(number=69, symbol='Tm', name='Thulium', mass=168.9342, category='lanthanide', period=9, group=15, summary='Soft grey metallic element that belongs to the lanthanoids. One natural isotope exists, Tm-169, and seventeen artificial isotopes have been produced. No known uses for the element. Discovered in 1879 by Per Theodor Cleve.', melting_point=1818.15, boiling_point=2223.15, phase='solid', density=9.321, electron_configuration='[Xe] 4f13 6s2', electronegativity=1.25, atomic_radius=175.0, oxidation_states='+3'),
    Element(number=70, symbol='Yb', name='Ytterbium', mass=173.045, category='lanthanide', period=9, group=16, summary='Silvery metallic element of the lanthanoids. Seven natural isotopes and ten artificial isotopes are known. Used in certain steels. Discovered by J.D.G. Marignac in 1878.', melting_point=1097.15, boiling_point=1469.15, phase='solid', density=6.9, electron_configuration='[Xe] 4f14 6s2', electronegativity=None, atomic_radius=175.0, oxidation_states='+3'),
    Element(number=71, symbol='Lu', name='Lutetium', mass=174.9668, category='lanthanide', period=9, group=17, summary='Silvery-white rare-earth metal which is relatively stable in air. It happens to be the most expensive rare-earth metal. Its found with almost all rare-earth metals, but is very difficult to separate from other elements. Least abundant of all natural elements. Used in metal alloys, and as a catalyst in various processes. There are two natural, stable isotopes, and seven radioisotopes, the most stable being Lu-174 with a half-life of 3.3 years. The separation of lutetium from Ytterbium was described by Georges Urbain in 1907. It was discovered at approximately the same time by Carl Auer von Welsbach. The name comes from the Greek word lutetia which means Paris.', melting_point=1936.15, boiling_point=3675.15, phase='solid', density=9.84, electron_configuration='[Xe] 4f14 5d 6s2', electronegativity=1.0, atomic_radius=175.0, oxidation_states='+3'),
    Element(number=72, symbol='Hf', name='Hafnium', mass=178.49, category='transition metal', period=6, group=4, summary='Silvery lustrous metallic transition element. Used in tungsten alloys in filaments and electrodes, also acts as a neutron absorber. First reported by Urbain in 1911, existence was finally established in 1923 by D. Coster, G.C. de Hevesy in 1923.', melting_point=2506.15, boiling_point=4873.15, phase='solid', density=13.3, electron_configuration='[Xe] 4f14 5d2 6s2', electronegativity=1.3, atomic_radius=155.0, oxidation_states='+4'),
    Element(number=73, symbol='Ta', name='Tantalum', mass=180.9479, category='transition metal', period=6, group=5, summary='Heavy blue-grey metallic transition element. Ta-181 is a stable isotope, and Ta-180 is a radioactive isotope, with a half-life in excess of 10^7 years. Used in surgery as it is unreactive. Forms a passive oxide layer in air. Identified in 1802 by Ekeberg and isolated in 1820 by Jons J. Berzelius.', melting_point=3290.15, boiling_point=5728.15, phase='solid', density=16.4, electron_configuration='[Xe] 4f14 5d3 6s2', electronegativity=1.5, atomic_radius=145.0, oxidation_states='+5'),
    Element(number=74, symbol='W', name='Tungsten', mass=183.84, category='transition metal', period=6, group=6, summary='White or grey metallic transition element,formerly called Wolfram. Forms a protective oxide in air and can be oxidized at high temperature. First isolated by Jose and Fausto de Elhuyer in 1783.', melting_point=3687.15, boiling_point=5828.15, phase='solid', density=19.3, electron_configuration='[Xe] 4f14 5d4 6s2', electronegativity=1.7, atomic_radius=135.0, oxidation_states='+6, +4'),
    Element(number=75, symbol='Re', name='Rhenium', mass=186.207, category='transition metal', period=6, group=7, summary='Silvery-white metallic transition element. Obtained as a by-product of molybdenum refinement. Rhenium-molybdenum alloys are superconducting.', melting_point=3458.15, boiling_point=5863.15, phase='solid', density=20.8, electron_configuration='[Xe] 4f14 5d5 6s2', electronegativity=1.9, atomic_radius=135.0, oxidation_states='+4'),
    Element(number=76, symbol='Os', name='Osmium', mass=190.23, category='transition metal', period=6, group=8, summary='Hard blue-white metallic transition element. Found with platinum and used in some alloys with platinum and iridium.', melting_point=3306.15, boiling_point=5281.15, phase='solid', density=22.5872, electron_configuration='[Xe] 4f14 5d6 6s2', electronegativity=2.2, atomic_radius=130.0, oxidation_states='+4'),
    Element(number=77, symbol='Ir', name='Iridium', mass=192.217, category='transition metal', period=6, group=9, summary='Very hard and brittle, silvery metallic transition element. It has a yellowish cast to it. Salts of iridium are highly colored. It is the most corrosion resistant metal known, not attacked by any acid, but is attacked by molten salts. There are two natural isotopes of iridium, and 4 radioisotopes, the most stable being Ir-192 with a half-life of 73.83 days. Ir-192 decays into Platinum, while the other radioisotopes decay into Osmium. Iridium is used in high temperature apparatus, electrical contacts, and as a hardening agent for platinumpy. Discovered in 1803 by Smithson Tennant in England. The name comes from the Greek word iris, which means rainbow. Iridium metal is generally non-toxic due to its relative unreactivity, but iridium compounds should be considered highly toxic.', melting_point=2719.15, boiling_point=4701.15, phase='solid', density=22.5622, electron_configuration='[Xe] 4f14 5d7 6s2', electronegativity=2.2, atomic_radius=135.0, oxidation_states='+4, +3'),
    Element(number=78, symbol='Pt', name='Platinum', mass=195.084, category='transition metal', period=6, group=10, summary='Attractive greyish-white metal. When pure, it is malleable and ductile. Does not oxidize in air, insoluble in hydrochloric and nitric acid. Corroded by halogens, cyandies, sulphur and alkalis. Hydrogen and Oxygen react explosively in the presence of platinumpy. There are six stable isotopes and three radioisotopes, the most stable being Pt-193 with a half-life of 60 years. Platinum is used in jewelry, laboratory equipment, electrical contacts, dentistry, and anti-pollution devices in cars. PtCl2(NH3)2 is used to treat some forms of cancer. Platinum-Cobalt alloys have magnetic properties. It is also used in the definition of the Standard Hydrogen Electrode. Discovered by Antonio de Ulloa in South America in 1735. The name comes from the Spanish word platina which means silver. Platinum metal is generally not a health concern due to its unreactivity, however platinum compounds should be considered highly toxic.', melting_point=2041.35, boiling_point=4098.15, phase='solid', density=21.5, electron_configuration='[Xe] 4f14 5d9 6s', electronegativity=2.2, atomic_radius=135.0, oxidation_states='+4, +2'),
    Element(number=79, symbol='Au', name='Gold', mass=196.9666, category='transition metal', period=6, group=11, summary='Gold is gold colored. It is the most malleable and ductile metal known. There is only one stable isotope of gold, and five radioisotopes of gold, Au-195 being the most stable with a half-life of 186 days. Gold is used as a monetary standard, in jewelry, dentistry, electronics. Au-198 is used in treating cancer and some other medical conditions. Gold has been known to exist as far back as 2600 BC. Gold comes from the Anglo-Saxon word gold. Its symbol, Au, comes from the Latin word aurum, which means gold. Gold is not particularly toxic, however it is known to cause damage to the liver and kidneys in some.', melting_point=1337.33, boiling_point=3109.15, phase='solid', density=19.3, electron_configuration='[Xe] 4f14 5d10 6s', electronegativity=2.4, atomic_radius=135.0, oxidation_states='+3'),
    Element(number=80, symbol='Hg', name='Mercury', mass=200.592, category='transition metal', period=6, group=12, summary='Heavy silvery liquid metallic element, belongs to the zinc group. Used in thermometers, barometers and other scientific apparatus. Less reactive than zinc and cadmium, does not displace hydrogen from acids. Forms a number of complexes and organomercury compounds.', melting_point=234.321, boiling_point=629.769, phase='liquid', density=13.5336, electron_configuration='[Xe] 4f14 5d10 6s2', electronegativity=1.9, atomic_radius=150.0, oxidation_states='+2, +1'),
    Element(number=81, symbol='Tl', name='Thallium', mass=204.38, category='post-transition metal', period=6, group=13, summary="Pure, unreacted thallium appears silvery-white and exhibits a metallic lustre. Upon reacting with air, it begins to turn bluish-grey and looks like lead. It is very malleable, and can be cut with a knife. There are two stable isotopes, and four radioisotopes, Tl-204 being the most stable with a half-life of 3.78 years. Thallium sulphate was used as a rodenticide. Thallium sulphine's conductivity changes with exposure to infrared light, this gives it a use in infrared detectors. Discovered by Sir William Crookes via spectroscopy. Its name comes from the Greek word thallos, which means green twig. Thallium and its compounds are toxic and can cause cancer.", melting_point=577.15, boiling_point=1746.15, phase='solid', density=11.8, electron_configuration='[Xe] 4f14 5d10 6s2 6p', electronegativity=1.8, atomic_radius=190.0, oxidation_states='+3, +1'),
    Element(number=82, symbol='Pb', name='Lead', mass=207.2, category='post-transition metal', period=6, group=14, summary='Heavy dull grey ductile metallic element, belongs to group 14. Used in building construction, lead-place accumulators, bullets and shot, and is part of solder, pewter, bearing metals, type metals and fusible alloys.', melting_point=600.612, boiling_point=2022.15, phase='solid', density=11.3, electron_configuration='[Xe] 4f14 5d10 6s2 6p2', electronegativity=1.8, atomic_radius=180.0, oxidation_states='+4, +2'),
    Element(number=83, symbol='Bi', name='Bismuth', mass=208.9804, category='post-transition metal', period=6, group=15, summary='White crystalline metal with a pink tinge, belongs to group 15. Most diamagnetic of all metals and has the lowest thermal conductivity of all the elements except mercury. Lead-free bismuth compounds are used in cosmetics and medical procedures. Burns in the air and produces a blue flame. In 1753, C.G. Junine first demonstrated that it was different from lead.', melting_point=544.552, boiling_point=1837.15, phase='solid', density=9.79, electron_configuration='[Xe] 4f14 5d10 6s2 6p3', electronegativity=1.9, atomic_radius=160.0, oxidation_states='+3'),
    Element(number=84, symbol='Po', name='Polonium', mass=209.0, category='post-transition metal', period=6, group=16, summary='Rare radioactive metallic element, belongs to group 16 of the periodic table. Over 30 known isotopes exist, the most of all elements. Po-209 has a half-life of 103 years. Possible uses in heating spacecraft. Discovered by Marie Curie in 1898 in a sample of pitchblende.', melting_point=527.15, boiling_point=1235.15, phase='solid', density=9.2, electron_configuration='[Xe] 4f14 5d10 6s2 6p4', electronegativity=2.0, atomic_radius=190.0, oxidation_states='+4, +2, -2'),
    Element(number=85, symbol='At', name='Astatine', mass=210.0, category='reactive nonmetal', period=6, group=17, summary='Radioactive halogen element. Occurs naturally from uranium and thorium decay. At least 20 known isotopes. At-210, the most stable, has a half-life of 8.3 hours. Synthesized by nuclear bombardment in 1940 by D.R. Corson, K.R. MacKenzie and E. Segre at the University of California.', melting_point=575.15, boiling_point=None, phase='solid', density=7.0, electron_configuration='[Xe] 4f14 5d10 6s2 6p5', electronegativity=2.2, atomic_radius=None, oxidation_states='+1, -1'),
    Element(number=86, symbol='Rn', name='Radon', mass=222.0, category='noble gas', period=6, group=18, summary='Colorless radioactive gaseous element, belongs to the noble gases. Of the twenty known isotopes, the most stable is Rn-222 with a half-life of 3.8 days. Formed by the radioactive decay of Radium-226. Radon itself decays into Polonium. Used in radiotherapy. As a noble gas, it is effectively inert, though radon fluoride has been synthesized. First isolated in 1908 by Ramsey and Gray.', melting_point=202.15, boiling_point=211.45, phase='gas', density=0.0091, electron_configuration='[Xe] 4f14 5d10 6s2 6p6', electronegativity=None, atomic_radius=None, oxidation_states=''),
    Element(number=87, symbol='Fr', name='Francium', mass=223.0, category='alkali metal', period=7, group=1, summary='Radioactive element, belongs to group 1 of the periodic table. Found in uranium and thorium ores. The 22 known isotopes are all radioactive, with the most stable being Fr-223. Its existence was confirmed in 1939 by Marguerite Perey.', melting_point=294.15, boiling_point=None, phase='liquid', density=1.87, electron_configuration='[Rn] 7s', electronegativity=0.7, atomic_radius=None, oxidation_states='+1'),
    Element(number=88, symbol='Ra', name='Radium', mass=226.0, category='alkaline earth metal', period=7, group=2, summary='Radioactive metallic transuranic element, belongs to group 2 of the periodic table. Most stable isotope, Ra-226 has a half-life of 1602 years, which decays into radon. Isolated from pitchblende in 1898 Marie and Pierre Curie.', melting_point=969.15, boiling_point=None, phase='solid', density=5.0, electron_configuration='[Rn] 7s2', electronegativity=0.9, atomic_radius=215.0, oxidation_states='+2'),
    Element(number=89, symbol='Ac', name='Actinium', mass=227.0, category='actinide', period=10, group=3, summary='Silvery radioactive metallic element, belongs to group 3 of the periodic table. The most stable isotope, Ac-227, has a half-life of 217 years. Ac-228 (half-life of 6.13 hours) also occurs in nature. There are 22 other artificial isotopes, all radioactive and having very short half-lives. Chemistry similar to lanthanumpy. Used as a source of alpha particles. Discovered by A. Debierne in 1899.', melting_point=1323.15, boiling_point=3473.15, phase='solid', density=10.0, electron_configuration='[Rn] 6d 7s2', electronegativity=1.1, atomic_radius=195.0, oxidation_states='+3'),
    Element(number=90, symbol='Th', name='Thorium', mass=232.0377, category='actinide', period=10, group=4, summary='Grey radioactive metallic element. Belongs to actinoids. Found in monazite sand in Brazil, India and the US. Thorium-232 has a half-life of 1.39x10^10 years. Can be used as a nuclear fuel for breeder reactors. Thorium-232 captures slow Neutrons and breeds uranium-233. Discovered by Jons J. Berzelius in 1829.', melting_point=2023.15, boiling_point=5058.15, phase='solid', density=11.7, electron_configuration='[Rn] 6d2 7s2', electronegativity=1.3, atomic_radius=180.0, oxidation_states='+4'),
    Element(number=91, symbol='Pa', name='Protactinium', mass=231.0359, category='actinide', period=10, group=5, summary='Radioactive metallic element, belongs to the actinoids. The most stable isotope, Pa-231 has a half-life of 2.43*10^4 years. At least 10 other radioactive isotopes are known. No practical applications are known. Discovered in 1917 by Lise Meitner and Otto Hahn.', melting_point=1845.15, boiling_point=None, phase='solid', density=15.4, electron_configuration='[Rn] 5f2 6d 7s2', electronegativity=1.5, atomic_radius=180.0, oxidation_states='+5'),
    Element(number=92, symbol='U', name='Uranium', mass=238.0289, category='actinide', period=10, group=6, summary='White radioactive metallic element belonging to the actinoids. Three natural isotopes, U-238, U-235 and U-234. Uranium-235 is used as the fuel for nuclear reactors and weapons. Discovered by Martin H. Klaproth in 1789.', melting_point=1408.15, boiling_point=4404.15, phase='solid', density=19.1, electron_configuration='[Rn] 5f3 6d 7s2', electronegativity=1.7, atomic_radius=175.0, oxidation_states='+6'),
    Element(number=93, symbol='Np', name='Neptunium', mass=237.0, category='actinide', period=10, group=7, summary='Radioactive metallic transuranic element, belongs to the actinoids. Np-237, the most stable isotope, has a half-life of 2.2*10^6 years and is a by product of nuclear reactors. The other known isotopes have mass numbers 229 through 236, and 238 through 241. Np-236 has a half-life of 5*10^3 years. First produced by Edwin M. McMillan and P.H. Abelson in 1940.', melting_point=917.15, boiling_point=None, phase='solid', density=20.2, electron_configuration='[Rn] 5f4 6d 7s2', electronegativity=1.3, atomic_radius=175.0, oxidation_states='+5'),
    Element(number=94, symbol='Pu', name='Plutonium', mass=244.0, category='actinide', period=10, group=8, summary='Dense silvery radioactive metallic transuranic element, belongs to the actinoids. Pu-244 is the most stable isotope with a half-life of 7.6*10^7 years. Thirteen isotopes are known. Pu-239 is the most important, it undergoes nuclear fission with slow neutrons and is hence important to nuclear weapons and reactors. Plutonium production is monitored down to the gram to prevent military misuse. First produced by Gleen T. Seaborg, Edwin M. McMillan, J.W. Kennedy and A.C. Wahl in 1940.', melting_point=913.15, boiling_point=3501.15, phase='solid', density=19.7, electron_configuration='[Rn] 5f6 7s2', electronegativity=1.3, atomic_radius=175.0, oxidation_states='+4'),
    Element(number=95, symbol='Am', name='Americium', mass=243.0, category='actinide', period=10, group=9, summary='Radioactive metallic transuranic element, belongs to the actinoids. Ten known isotopes. Am-243 is the most stable isotope, with a half-life of 7.95*10^3 years. Discovered by Glenn T. Seaborg and associates in 1945, it was obtained by bombarding Uranium-238 with alpha particles.', melting_point=1449.15, boiling_point=None, phase='solid', density=12.0, electron_configuration='[Rn] 5f7 7s2', electronegativity=None, atomic_radius=175.0, oxidation_states='+3'),
    Element(number=96, symbol='Cm', name='Curium', mass=247.0, category='actinide', period=10, group=10, summary='Radioactive metallic transuranic element. Belongs to actinoid series. Nine known isotopes, Cm-247 has a half-life of 1.64*10^7 years. First identified by Glenn T. Seaborg and associates in 1944, first produced by L.B. Werner and I. Perlman in 1947 by bombarding americium-241 with Neutrons. Named for Marie Curie.', melting_point=1618.15, boiling_point=None, phase='solid', density=13.51, electron_configuration='[Rn] 5f7 6d 7s2', electronegativity=None, atomic_radius=None, oxidation_states='+3'),
    Element(number=97, symbol='Bk', name='Berkelium', mass=247.0, category='actinide', period=10, group=11, summary='Radioactive metallic transuranic element. Belongs to actinoid series. Eight known isotopes, the most common Bk-247, has a half-life of 1.4*10^3 years. First produced by Glenn T. Seaborg and associates in 1949 by bombarding americium-241 with alpha particles.', melting_point=1259.15, boiling_point=None, phase='solid', density=14.78, electron_configuration='[Rn] 5f9 7s2', electronegativity=None, atomic_radius=None, oxidation_states='+3'),
    Element(number=98, symbol='Cf', name='Californium', mass=251.0, category='actinide', period=10, group=12, summary='Radioactive metallic transuranic element. Belongs to actinoid series. Cf-251 has a half life of about 700 years. Nine isotopes are known. Cf-252 is an intense Neutron source, which makes it an intense Neutron source and gives it a use in Neutron activation analysis and a possible use as a radiation source in medicine. First produced by Glenn T. Seaborg and associates in 1950.', melting_point=1173.15, boiling_point=None, phase='solid', density=15.1, electron_configuration='[Rn] 5f10 7s2', electronegativity=None, atomic_radius=None, oxidation_states='+3'),
    Element(number=99, symbol='Es', name='Einsteinium', mass=252.0, category='actinide', period=10, group=13, summary='Appearance is unknown, however it is most probably metallic and silver or gray in color. Radioactive metallic transuranic element belonging to the actinoids. Es-254 has the longest half-life of the eleven known isotopes at 270 days. First identified by Albert Ghiorso and associates in the debris of the 1952 hydrogen bomb explosion. In 1961 the first microgram quantities of Es-232 were separated. While einsteinium never exists naturally, if a sufficient amount was assembled, it would pose a radiation hazard.', melting_point=1133.15, boiling_point=None, phase='solid', density=8.84, electron_configuration='[Rn] 5f11 7s2', electronegativity=None, atomic_radius=None, oxidation_states='+3'),
    Element(number=100, symbol='Fm', name='Fermium', mass=257.0, category='actinide', period=10, group=14, summary='Radioactive metallic transuranic element, belongs to the actinoids. Ten known isotopes, most stable is Fm-257 with a half-life of 10 days. First identified by Albert Ghiorso and associates in the debris of the first hydrogen-bomb explosion in 1952.', melting_point=1800.15, boiling_point=None, phase='solid', density=9.7, electron_configuration='[Rn] 5f12 7s2', electronegativity=None, atomic_radius=None, oxidation_states='+3'),
    Element(number=101, symbol='Md', name='Mendelevium', mass=258.0, category='actinide', period=10, group=15, summary="Radioactive metallic transuranic element. Belongs to the actinoid series. Only known isotope, Md-256 has a half-life of 1.3 hours. First identified by Glenn T. Seaborg, Albert Ghiorso and associates in 1955. Alternative name Unnilunium has been proposed. Named after the 'inventor' of the periodic table, Dmitri Mendeleev.", melting_point=1100.15, boiling_point=None, phase='solid', density=10.3, electron_configuration='[Rn] 5f13 7s2', electronegativity=None, atomic_radius=None, oxidation_states='+3'),
    Element(number=102, symbol='No', name='Nobelium', mass=259.0, category='actinide', period=10, group=16, summary='Radioactive metallic transuranic element, belongs to the actinoids. Seven known isotopes exist, the most stable being No-254 with a half-life of 255 seconds. First identified with certainty by Albert Ghiorso and Glenn T. Seaborg in 1966. Unnilbium has been proposed as an alternative name.', melting_point=1100.15, boiling_point=None, phase='solid', density=9.9, electron_configuration='[Rn] 5f14 7s2', electronegativity=None, atomic_radius=None, oxidation_states='+3'),
    Element(number=103, symbol='Lr', name='Lawrencium', mass=262.0, category='actinide', period=10, group=17, summary='Appearance unknown, however it is most likely silvery-white or grey and metallic. Lawrencium is a synthetic rare-earth metal. There are eight known radioisotopes, the most stable being Lr-262 with a half-life of 3.6 hours. Due to the short half-life of lawrencium, and its radioactivity, there are no known uses for it. Identified by Albert Ghiorso in 1961 at Berkeley. It was produced by bombarding californium with boron ions. The name is temporary IUPAC nomenclature, the origin of the name comes from Ernest O. Lawrence, the inventor of the cyclotron. If sufficient amounts of lawrencium were produced, it would pose a radiation hazard.', melting_point=1900.15, boiling_point=None, phase='solid', density=15.6, electron_configuration='[Rn] 5f14 7s2 7p1', electronegativity=None, atomic_radius=None, oxidation_states='+3'),
    Element(number=104, symbol='Rf', name='Rutherfordium', mass=267.0, category='transition metal', period=7, group=4, summary='Radioactive transactinide element. Expected to have similar chemical properties to those displayed by hafnium. Rf-260 was discovered by the Joint Nuclear Research Institute at Dubna (U.S.S.R.) in 1964. Researchers at Berkeley discovered Unq-257 and Unq-258 in 1964.', melting_point=None, boiling_point=None, phase='unknown', density=23.3, electron_configuration='[Rn] 5f14 6d2 7s2', electronegativity=None, atomic_radius=None, oxidation_states='+4'),
    Element(number=105, symbol='Db', name='Dubnium', mass=268.0, category='transition metal', period=7, group=5, summary='Also known as Hahnium, Ha. Radioactive transactinide element. Half-life of 1.6s. Discovered in 1970 by Berkeley researchers. So far, seven isotopes have been discovered.', melting_point=None, boiling_point=None, phase='unknown', density=29.3, electron_configuration='[Rn] 5f14 6d3 7s2', electronegativity=None, atomic_radius=None, oxidation_states=''),
    Element(number=106, symbol='Sg', name='Seaborgium', mass=271.0, category='transition metal', period=7, group=6, summary='Half-life of 0.9 +/- 0.2 s. Discovered by the Joint Institute for Nuclear Research at Dubna (U.S.S.R.) in June of 1974. Its existence was confirmed by the Lawrence Berkeley Laboratory and Livermore National Laboratory in September of 1974.', melting_point=None, boiling_point=None, phase='unknown', density=35.0, electron_configuration='[Rn] 5f14 6d4 7s2', electronegativity=None, atomic_radius=None, oxidation_states=''),
    Element(number=107, symbol='Bh', name='Bohrium', mass=274.0, category='transition metal', period=7, group=7, summary='Radioactive transition metal. Half-life of approximately 1/500 s. Discovered by the Joint Institute for Nuclear Research at Dubna (U.S.S.R.) in 1976. Confirmed by West German physicists at the Heavy Ion Research Laboratory at Darmstadt.', melting_point=None, boiling_point=None, phase='unknown', density=37.1, electron_configuration='[Rn] 5f14 6d5 7s2', electronegativity=None, atomic_radius=None, oxidation_states=''),
    Element(number=108, symbol='Hs', name='Hassium', mass=269.0, category='transition metal', period=7, group=8, summary='Radioactive transition metal first synthesized in 1984 by a German research team led by Peter Armbruster and Gottfried Muenzenberg at the Institute for Heavy Ion Research at Darmstadt.', melting_point=None, boiling_point=None, phase='unknown', density=40.7, electron_configuration='[Rn] 5f14 6d6 7s2', electronegativity=None, atomic_radius=None, oxidation_states=''),
    Element(number=109, symbol='Mt', name='Meitnerium', mass=276.0, category='unknown', period=7, group=9, summary='Half-life of approximately 5 ms. The creation of this element demonstrated that fusion techniques could indeed be used to make new, heavy nuclei. Made and identified by physicists of the Heavy Ion Research Laboratory, Darmstadt, West Germany in 1982. Named in honor of Lise Meitner, the Austrian physicist.', melting_point=None, boiling_point=None, phase='unknown', density=37.4, electron_configuration='[Rn] 5f14 6d7 7s2', electronegativity=None, atomic_radius=None, oxidation_states=''),
    Element(number=110, symbol='Ds', name='Darmstadtium', mass=281.0, category='unknown', period=7, group=10, summary='It has no significant commercial applications.', melting_point=None, boiling_point=None, phase='unknown', density=34.8, electron_configuration='[Rn] 5f14 6d9 7s1', electronegativity=None, atomic_radius=None, oxidation_states=''),
    Element(number=111, symbol='Rg', name='Roentgenium', mass=281.0, category='unknown', period=7, group=11, summary='It has no significant commercial applications.', melting_point=None, boiling_point=None, phase='unknown', density=28.7, electron_configuration='[Rn] 5f14 6d10 7s1', electronegativity=None, atomic_radius=None, oxidation_states=''),
    Element(number=112, symbol='Cn', name='Copernicium', mass=285.0, category='transition metal', period=7, group=12, summary='It has no significant commercial applications.', melting_point=None, boiling_point=None, phase='unknown', density=14.0, electron_configuration='[Rn] 5f14 6d10 7s2', electronegativity=None, atomic_radius=None, oxidation_states=''),
    Element(number=113, symbol='Nh', name='Nihonium', mass=286.0, category='post-transition metal', period=7, group=13, summary='Synthetic superheavy element, first synthesized in 2015 by RIKEN (Japan). Named after the country of Japan.', melting_point=None, boiling_point=None, phase='unknown', density=16.0, electron_configuration='[Rn] 5f14 6d10 7s2 7p1', electronegativity=None, atomic_radius=None, oxidation_states=''),
    Element(number=114, symbol='Fl', name='Flerovium', mass=289.0, category='post-transition metal', period=7, group=14, summary='Synthetic superheavy element, first synthesized in 1998 by Joint Institute for Nuclear Research (Russia). Named after the Flerov Laboratory of Nuclear Reactions of the Joint Institute for Nuclear Research in Dubna, Russia.', melting_point=None, boiling_point=None, phase='unknown', density=9.928, electron_configuration='[Rn] 5f14 6d10 7s2 7p2', electronegativity=None, atomic_radius=None, oxidation_states=''),
    Element(number=115, symbol='Mc', name='Moscovium', mass=288.0, category='post-transition metal', period=7, group=15, summary='Synthetic superheavy element, first synthesized in 2003 by Joint Institute for Nuclear Research (Russia). Named after the city of Moscov.', melting_point=None, boiling_point=None, phase='unknown', density=13.5, electron_configuration='[Rn] 5f14 6d10 7s2 7p3', electronegativity=None, atomic_radius=None, oxidation_states=''),
    Element(number=116, symbol='Lv', name='Livermorium', mass=293.0, category='post-transition metal', period=7, group=16, summary='Synthetic superheavy element, first synthesized in 2000 by Lawrence Livermore National Laboratory (United States). Named after the Lawrence Livermore National Laboratory in the United States.', melting_point=None, boiling_point=None, phase='unknown', density=12.9, electron_configuration='[Rn] 5f14 6d10 7s2 7p4', electronegativity=None, atomic_radius=None, oxidation_states=''),
    Element(number=117, symbol='Ts', name='Tennessine', mass=294.0, category='reactive nonmetal', period=7, group=17, summary='Synthetic superheavy element, first synthesized in 2010 by Joint Institute for Nuclear Research/Oak Ridge National Laboratory (Russia/United States). Named after the state of Tennessee in United States.', melting_point=None, boiling_point=None, phase='unknown', density=7.2, electron_configuration='[Rn] 5f14 6d10 7s2 7p5', electronegativity=None, atomic_radius=None, oxidation_states=''),
    Element(number=118, symbol='Og', name='Oganesson', mass=294.0, category='noble gas', period=7, group=18, summary='Synthetic superheavy element, first synthesized in 2002 by Joint Institute for Nuclear Research (Russia). Named in honor of the scientist Yuri Oganessian.', melting_point=None, boiling_point=None, phase='unknown', density=7.0, electron_configuration='[Rn] 5f14 6d10 7s2 7p6', electronegativity=None, atomic_radius=None, oxidation_states=''),
]

ELEMENTS_BY_NUMBER: dict[int, Element] = {e.number: e for e in ELEMENTS}
