"""Regenerate ``src/periodic_table_tui/data.py`` with extra chemistry fields.

Sourced from the ``mendeleev`` package (a dev-only dependency, not used at
runtime). Queries its bundled SQLite database directly instead of going
through the ``mendeleev`` ORM, which takes upwards of ten seconds to load all
118 elements one at a time.

Run with: ``uv run python scripts/generate_data.py`` (or ``pixi run gen-data``).
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

import mendeleev

ROOM_TEMPERATURE_K = 298.15

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_PY = REPO_ROOT / "src" / "periodic_table_tui" / "data.py"


def _phase_at_room_temperature(melting_point: float | None, boiling_point: float | None) -> str:
    """Best-effort phase at 298.15 K, tolerant of a missing melting or boiling point.

    A handful of elements (e.g. helium, which doesn't solidify at normal
    pressure; carbon, which sublimes) only have one of the two values
    recorded in the source data.
    """
    if boiling_point is not None and boiling_point <= ROOM_TEMPERATURE_K:
        return "gas"
    if melting_point is not None and melting_point <= ROOM_TEMPERATURE_K:
        return "liquid"
    if melting_point is not None or boiling_point is not None:
        return "solid"
    return "unknown"


PhaseTransition = tuple[float | None, float | None]


def _fetch_phase_transitions(cursor: sqlite3.Cursor) -> dict[int, PhaseTransition]:
    cursor.execute(
        "SELECT atomic_number, MIN(id), melting_point, boiling_point "
        "FROM phasetransitions GROUP BY atomic_number"
    )
    return {row[0]: (row[2], row[3]) for row in cursor.fetchall()}


def _fetch_oxidation_states(cursor: sqlite3.Cursor) -> dict[int, str]:
    cursor.execute(
        "SELECT atomic_number, oxidation_state FROM oxidationstates "
        "WHERE category = 'main' ORDER BY atomic_number, oxidation_state DESC"
    )
    states: dict[int, list[int]] = {}
    for atomic_number, state in cursor.fetchall():
        states.setdefault(atomic_number, []).append(state)
    return {
        number: ", ".join(f"{s:+d}" for s in values) if values else ""
        for number, values in states.items()
    }


def _fetch_elements(cursor: sqlite3.Cursor) -> dict[int, sqlite3.Row]:
    cursor.execute(
        "SELECT atomic_number, atomic_radius, density, electronic_configuration, "
        "en_pauling FROM elements"
    )
    return {row["atomic_number"]: row for row in cursor.fetchall()}


def fetch_extra_fields() -> dict[int, dict[str, object]]:
    db_path = Path(mendeleev.__file__).parent / "elements.db"
    con = sqlite3.connect(db_path)
    con.row_factory = sqlite3.Row
    cursor = con.cursor()

    elements = _fetch_elements(cursor)
    phase_transitions = _fetch_phase_transitions(cursor)
    oxidation_states = _fetch_oxidation_states(cursor)
    con.close()

    extra: dict[int, dict[str, object]] = {}
    for number, row in elements.items():
        melting_point, boiling_point = phase_transitions.get(number, (None, None))
        extra[number] = {
            "melting_point": melting_point,
            "boiling_point": boiling_point,
            "phase": _phase_at_room_temperature(melting_point, boiling_point),
            "density": row["density"],
            "electron_configuration": row["electronic_configuration"] or "",
            "electronegativity": row["en_pauling"],
            "atomic_radius": row["atomic_radius"],
            "oxidation_states": oxidation_states.get(number, ""),
        }
    return extra


def _load_current_elements() -> list:
    from periodic_table_tui.data import ELEMENTS

    return ELEMENTS


def _format_float(value: float | None) -> str:
    return "None" if value is None else repr(round(value, 4))


def render_data_py(elements: list, extra_fields: dict[int, dict[str, object]]) -> str:
    lines = [
        '"""Static data for all 118 elements of the periodic table.',
        "",
        "Grid coordinates (`period`, `group`) follow the standard 18-group layout,",
        "with lanthanides and actinides placed on two separate rows below the main",
        "body (periods 8 and 9 in this grid, groups 3-17).",
        "",
        "Base fields (number, symbol, name, mass, category, period, group, summary)",
        "are hand-authored. The chemistry fields below that (melting_point through",
        "oxidation_states) are generated by scripts/generate_data.py from the",
        "`mendeleev` package's data — regenerate with `uv run python scripts/generate_data.py`.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "",
        "",
        "@dataclass(frozen=True, slots=True)",
        "class Element:",
        "    number: int",
        "    symbol: str",
        "    name: str",
        "    mass: float",
        "    category: str",
        "    period: int",
        "    group: int",
        "    summary: str",
        "    melting_point: float | None  # kelvin",
        "    boiling_point: float | None  # kelvin",
        '    phase: str  # "solid", "liquid", "gas", or "unknown" at room temperature',
        "    density: float | None  # g/cm^3",
        "    electron_configuration: str",
        "    electronegativity: float | None  # Pauling scale",
        "    atomic_radius: float | None  # picometers",
        "    oxidation_states: str",
        "",
        "",
        "CATEGORY_COLORS: dict[str, str] = {",
        '    "alkali metal": "#ff8a65",',
        '    "alkaline earth metal": "#ffd54f",',
        '    "transition metal": "#90caf9",',
        '    "post-transition metal": "#a5d6a7",',
        '    "metalloid": "#ce93d8",',
        '    "reactive nonmetal": "#fff59d",',
        '    "noble gas": "#80deea",',
        '    "lanthanide": "#f48fb1",',
        '    "actinide": "#ef9a9a",',
        '    "unknown": "#bdbdbd",',
        "}",
        "",
        "ELEMENTS: list[Element] = [",
    ]

    for element in elements:
        fields = extra_fields.get(element.number, {})
        lines.append(
            "    Element("
            f"number={element.number}, "
            f"symbol={element.symbol!r}, "
            f"name={element.name!r}, "
            f"mass={element.mass!r}, "
            f"category={element.category!r}, "
            f"period={element.period}, "
            f"group={element.group}, "
            f"summary={element.summary!r}, "
            f"melting_point={_format_float(fields.get('melting_point'))}, "
            f"boiling_point={_format_float(fields.get('boiling_point'))}, "
            f"phase={fields.get('phase', 'unknown')!r}, "
            f"density={_format_float(fields.get('density'))}, "
            f"electron_configuration={fields.get('electron_configuration', '')!r}, "
            f"electronegativity={_format_float(fields.get('electronegativity'))}, "
            f"atomic_radius={_format_float(fields.get('atomic_radius'))}, "
            f"oxidation_states={fields.get('oxidation_states', '')!r}),"
        )

    lines.append("]")
    lines.append("")
    lines.append("ELEMENTS_BY_NUMBER: dict[int, Element] = {e.number: e for e in ELEMENTS}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    current_elements = _load_current_elements()
    extra_fields = fetch_extra_fields()
    rendered = render_data_py(current_elements, extra_fields)
    DATA_PY.write_text(rendered)
    print(f"Wrote {DATA_PY} with {len(current_elements)} elements.")


if __name__ == "__main__":
    main()
